### ISSUE TITLE
Doesn't work on Server [Fabric]

### ISSUE THREAD

**Issue by ShabanPlayz** [JSJBDEV/PlatosTransporters#24]
Server immediately crashes

[11:48:28] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'platos'
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:268) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:93) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_304
        at gd.rf.acro.platos.PlatosTransporters.<clinit>(PlatosTransporters.java:61) ~[platos-transporters-1.16-1.6.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:166) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at gd.rf.acro.platos.PlatosTransporters.<clinit>(PlatosTransporters.java:61) ~[platos-transporters-1.16-1.6.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
        ... 19 more

**Comment by JSJBDEV** [comment]
this is most probably due to a new version of fabric being used than this was compiled for
I will have to be doing updates soon so I guess ill end up using a new version

**Comment by JSJBDEV** [comment]
also what verison of platos are you using and what minecraft version?

**Comment by ShabanPlayz** [comment]
MC 1.16.3 and platos 1.16-1.6-TEST. It's not an issue with my version of fabric since the previous version did work fine on the server. Well, apart from the airships not flying and only being controllable while in water.

**Comment by JSJBDEV** [comment]
This should be fixed on 1.6.1 fabric :)
