### ISSUE TITLE
Forge Server Can't Connect With Plato's Transporters Installed

### ISSUE THREAD

**Issue by Silentbeard** [JSJBDEV/PlatosTransporters#36]
Greetings,
I set up a forge server and it works for the few mods my friend and I have been using (list below), but when I add Platos Transporters mod, we are rejected from the server with an error of an incomplete set of tags. I copied the file directly from the forge server and explored the jar file to make sure the tags weren't wiped out some how. They are in the jar file.

When I remove the mod from the client side (remains on server), I can connect with no issue but the mod does not work. When I removed the mod from the server side (remains on client) the issue appears. That strikes me as though the server is not properly loading the mod. I am able to play a single player game with the mod list below without issue and all mods work.

Please let me know if you need more information, I am new to Minecraft so I may need a little guidance.

**_Minecraft Version_:** 1.16.4

**_MOD List_:**
Better Weather
Optifine
BiomesOPlenty
JEI
Platos Transporters
Xaeros Minimap

**_Server side log:_**
[21:13:03] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

[21:13:03] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, u/e, dd12be42-52a9-4a91-a8a1-11c01849e498]

[21:13:03] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]

[21:13:03] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]

[21:13:03] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]

[21:13:03] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]

[21:13:03] [main/INFO]: Reloading ResourceManager: Default

[21:13:04] [Worker-Main-13/INFO]: Loaded 7 recipes

[21:13:04] [Worker-Main-13/INFO]: Loaded 927 advancements

[21:13:05] [Server thread/INFO]: Starting minecraft server version 1.16.4

[21:13:05] [Server thread/INFO]: Loading properties

[21:13:05] [Server thread/INFO]: Default game type: SURVIVAL

[21:13:05] [Server thread/INFO]: Generating keypair

[21:13:05] [Server console handler/ERROR]: Exception handling console input

java.io.IOException: The handle is invalid

at java.io.FileInputStream.readBytes(Native Method) \~\[?:1.8.0\_271\]

at [java.io.FileInputStream.read](https://java.io.FileInputStream.read)(Unknown Source) \~\[?:1.8.0\_271\]

at java.io.BufferedInputStream.read1(Unknown Source) \~\[?:1.8.0\_271\]

at [java.io.BufferedInputStream.read](https://java.io.BufferedInputStream.read)(Unknown Source) \~\[?:1.8.0\_271\]

at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) \~\[?:1.8.0\_271\]

at sun.nio.cs.StreamDecoder.implRead(Unknown Source) \~\[?:1.8.0\_271\]

at [sun.nio.cs.StreamDecoder.read](https://sun.nio.cs.StreamDecoder.read)(Unknown Source) \~\[?:1.8.0\_271\]

at [java.io.InputStreamReader.read](https://java.io.InputStreamReader.read)(Unknown Source) \~\[?:1.8.0\_271\]

at java.io.BufferedReader.fill(Unknown Source) \~\[?:1.8.0\_271\]

at java.io.BufferedReader.readLine(Unknown Source) \~\[?:1.8.0\_271\]

at java.io.BufferedReader.readLine(Unknown Source) \~\[?:1.8.0\_271\]

at [zg$1.run](https://zg$1.run)(SourceFile:95) \[minecraft\_server.1.16.4.jar:?\]

[21:13:05] [Server thread/INFO]: Starting Minecraft server on REMOVED BY OP

[21:13:05] [Server thread/INFO]: Using default channel type

[21:13:06] [Server thread/INFO]: Preparing level "world"

[21:13:06] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld

[21:13:07] [Server thread/INFO]: Preparing spawn area: 0%

[21:13:07] [Server thread/INFO]: Preparing spawn area: 0%

[21:13:07] [Server thread/INFO]: Time elapsed: 886 ms

[21:13:07] [Server thread/INFO]: Done (0.945s)! For help, type "help"

[21:14:32] [User Authenticator #1/INFO]: UUID of player Joe

[21:14:32] [Server thread/INFO]: REMOVED BY OP logged in with entity id 68 at (-2283.7293015580317, 67.0, 198.02648792917853)

[21:14:32] [Server thread/INFO]: Joe joined the game

[21:14:33] [Server thread/INFO]: Joe lost connection: Disconnected

**_Client Side Log (snippet where I think problem may be, can provide full if requested):_**

13Feb2021 21:14:33.407] [Render thread/INFO] [mezz.jei.util.LoggedTimer/]: Starting JEI took 317.4 ms

[13Feb2021 21:14:33.412] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Incomplete server tags, disconnecting. Missing: {minecraft:block=[platos:boat_material_blacklist, platos:boat_material, platos:scytheable]}

[13Feb2021 21:14:33.802] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program loaded: shadow

[13Feb2021 21:14:33.804] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Program loaded: gbuffers_basic

[13Feb2021 21:14:33.808] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Shader info log: /shaders/gbuffers_textured.fsh

0(543) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(544) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(545) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(546) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(547) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(548) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(550) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(551) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(552) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(553) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(555) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(557) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(559) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(561) : warning C7555: 'varying' is deprecated, use 'in/out' instead

0(598) : warning C7533: global variable gl_FragData is deprecated after version 120

[13Feb2021 21:14:33.809] [Render thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Info log: gbuffers_textured

**Comment by JSJBDEV** [comment]
This a strange error that I don't think existed in previous forge versions. you may want to check the previous version of Plato's just in case that works, I would also suggest trying without optifine altogether as it generally causes more problems then solutions in 1.16+ there is other performance mods like foamflower available. I'm.not fully able to do updates now due to various things but I will check to see if there is anything obviously wrong in my build

**Comment by JSJBDEV** [comment]
this may be fixed now
