### ISSUE TITLE
can't get back on ship

### ISSUE THREAD

**Issue by peanutinky** [JSJBDEV/PlatosTransporters#5]
when you exit the ship you can't get back on. the crash has been fix but not the exiting the ship to get back on

**Comment by JSJBDEV** [comment]
Did you try punching the ship and then getting back on?

**Comment by 1a2s3d4f1** [comment]
error log (try back on)
```
[12:34:51] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at gd.rf.acro.platos.entity.BlockShipEntity.method_5664(BlockShipEntity.java:241) ~[platos-transporters-1.16-1.3.1.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1227) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:74) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_2600$$Lambda$5716/0000000000000000.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.16.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) [intermediary-1.16.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) [intermediary-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zkl000$modifiedRunLoop(MinecraftServer.java:2765) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) [intermediary-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5008/0000000000000000.run(Unknown Source) [intermediary-1.16.1.jar:?]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_262]
[12:35:50] [main/WARN]: Received passengers for unknown entity
```

**Comment by JSJBDEV** [comment]
the error log appears to be a separate issue to do with the lift jack, it is fixed, but isn't to do with this

**Comment by JSJBDEV** [comment]
im looking into this error now

**Comment by JSJBDEV** [comment]
I have a feeling this may be due to the size of your ship, as the ship hitbox is quite small so you have to be right in the centre of it to actually be able to get on it

**Comment by JSJBDEV** [comment]
also you must use an empty hand to get on the ship

**Comment by JSJBDEV** [comment]
I believe your errors stem from the above, please reopen the issue if it persists after trying these, I will also release a minor update to fix that bug in the crashlog

**Comment by peanutinky** [comment]
i have tried to hit the ship in the center and i still could not get back on

**Comment by JSJBDEV** [comment]
Are you using an empty hand? Can you recreate this with other ships?

**Comment by JSJBDEV** [comment]
I so far haven't been able to recreate this issue, have you done what I said in my last message?

**Comment by Miros77** [comment]
> i have tried to hit the ship in the center and i still could not get back on

 press Shift  and /kill

**Comment by JSJBDEV** [comment]
I should probably look at that if it's still a problem, I'm not sure why it's a problem that xD I think I'm going to add remote disassembly and a few other things for this reason

**Comment by JSJBDEV** [comment]
supported on all new versions using the boarding stairs
